monitoring:
  enabled: true

# Required in this setup so the operator can discover block devices and create OSD prepare jobs.
enableDiscoveryDaemon: true

csi:
  enableRbdDriver: true
  enableCephfsDriver: true

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
