[stacked]
node1 ansible_host=10.196.242.4
node2 ansible_host=10.196.244.23
node3 ansible_host=10.196.245.6

[control]
node1
node2
node3

[workers]
node1
node2
node3

[all:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
