apiVersion: v1
kind: Namespace
metadata:
  name: velero
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: velero
  name: minio
  labels:
    component: minio
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: minio
  template:
    metadata:
      labels:
        component: minio
    spec:
      # Sørger for at mappen 'velero' eksisterer med riktige rettigheter
      initContainers:
      - name: create-bucket
        image: busybox
        command: ['sh', '-c', 'mkdir -p /data/velero && chmod -R 777 /data/velero']
        volumeMounts:
        - name: storage
          mountPath: /data
      containers:
      - name: minio
        image: minio/minio:latest
        args:
        - server
        - /data
        env:
        - name: MINIO_ROOT_USER
          value: minioadmin
        - name: MINIO_ROOT_PASSWORD
          value: minioadmin
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - name: storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: velero
  name: minio
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: s3
  selector:
    component: minio
