---
- name: Deploy rook-ceph on k8s
  hosts: control1
  vars:
    manifest_source_dir: "/home/ubuntu/project2/rook-manifests"

  tasks:
    - name: Add Rook repo
      shell: helm repo add rook-release https://charts.rook.io/release

    - name: Update Helm repos
      shell: helm repo update

    - name: Create namespace
      shell: kubectl create namespace rook-ceph || true

    - name: Install Rook Ceph Operator
      shell: |
        helm upgrade --install rook-ceph rook-release/rook-ceph \
        -n rook-ceph --create-namespace

    - name: Install Rook Ceph Cluster
      shell: |
        helm upgrade --install rook-ceph-cluster rook-release/rook-ceph-cluster \
        -n rook-ceph --create-namespace \
        --set cephClusterSpec.cephVersion.image=quay.io/ceph/ceph:v18 \
        --set cephClusterSpec.storage.useAllNodes=true \
        --set cephClusterSpec.storage.useAllDevices=true
