---
- name: Configure Docker Hub auth for containerd and kubelet
  hosts: all_vms
  become: true

  vars:
    docker_hub_username: "ENTER USERNAME HERE"
    docker_hub_password: "ENTER TOKEN HERE"

  tasks:
    # auth through containerd cerd.d
    - name: Create directory for Docker Hub certs config
      ansible.builtin.file:
        path: /etc/containerd/certs.d/docker.io
        state: directory
        mode: '0755'

    - name: Add Docker Hub hosts config with auth
      ansible.builtin.copy:
        dest: /etc/containerd/certs.d/docker.io/hosts.toml
        content: |
          server = "https://registry-1.docker.io"

          [host."https://registry-1.docker.io"]
            capabilities = ["pull", "resolve"]
            header = { "Authorization" = ["Basic {{ (docker_hub_username + ':' + docker_hub_password) | b64encode }}"] }
        mode: '0644'
      register: containerd_auth_config

    # auth through kubelet
    - name: Create global docker config directory for kubelet
      ansible.builtin.file:
        path: /var/lib/kubelet
        state: directory
        mode: '0755'

    - name: Create credential file for kubelet
      ansible.builtin.copy:
        dest: /var/lib/kubelet/config.json
        content: |
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "auth": "{{ (docker_hub_username + ':' + docker_hub_password) | b64encode }}"
              }
            }
          }
        mode: '0600'
      register: kubelet_auth_config

    # cleanup from old files
    - name: Remove old ineffective block from config.toml
      ansible.builtin.blockinfile:
        path: /etc/containerd/config.toml
        marker: "# {mark} ANSIBLE MANAGED DOCKER HUB AUTH"
        state: absent

    - name: Restart services to apply changes
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop:
        - containerd
        - kubelet
      when: containerd_auth_config.changed or kubelet_auth_config.changed
