- name: Preconfiguraton of kubernetes-nodes
  hosts: all_vms
  become: true
  gather_facts: true

  tasks:
    - name: Update APT update_cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Deactivate swap
      command: swapoff -a
      when: ansible_facts['swaptotal_mb'] > 0

    - name: Remove swap from /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+.*)$'
        replace: '# \1'

    - name: Activate modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Configure sysctl for network
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        sysctl_file: /etc/sysctl.d/k8s.conf
        reload: yes
      loop:
        - { key: "net.bridge.bridge-nf-call-iptables", value: "1" }
        - { key: "net.bridge.bridge-nf-call-ip6tables", value: "1" }
        - { key: "net.ipv4.ip_forward", value: "1" }

    - name: Install Containerd and tools
      apt:
        name:
          - containerd
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
          - conntrack
        state: present
        update_cache: yes

    - name: Create a contanerd config folder
      file:
        path: /etc/containerd
        state: directory

    - name: Generate the containerd config file
      shell: containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Activate SystemCgroup in containerd config
      replace:
        path: /etc/containerd/config.toml
        regexp: "SystemdCgroup = false"
        replace: "SystemdCgroup = true"
      notify: restart containerd

    - name: Download the Kuernetes GPT key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        mode: "0644"

    - name: Add Kubernetes apt-repo
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
        state: present
        filename: kubernetes

    - name: Install kubelet, kubeadm and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Hold kubernetes packages so it doesn't update with apt-update which may break the clusters
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

  handlers:
    - name: restart containerd
      service:
        name: containerd
        state: restarted

    - name: Enable containerd
      systemd:
        name: containerd
        enabled: true
        state: started

- name: Install necessary packages for node1 for Kubernetes
  hosts: node1
  become: true
  tasks:
    - name: Install Helm
      shell: |
        curl https://get.helm.sh/helm-v3.14.4-linux-amd64.tar.gz -o helm.tar.gz
        tar -xvf helm.tar.gz
        mv linux-amd64/helm /usr/local/bin/helm
      args:
        creates: /usr/local/bin/helm

    - name: Install pip
      ansible.builtin.apt:
        name:
          - curl
          - apt-transport-https
          - python3-pip
        state: present
        update_cache: yes

    - name: Install kubernetes python-library
      ansible.builtin.pip:
        name: "kubernetes>=24.2.0"
        executable: pip3
        extra_args: --break-system-packages
        state: present
