- name: Wait for vms to become reachable
  hosts: all_vms
  gather_facts: false
  tasks:
    - name: wait for ssh to be available
      wait_for_connection:
        timeout: 120
        delay: 10

    - name: Vent på at cloud-init er ferdig (låser opp APT)
      raw: cloud-init status --wait
      changed_when: false
      failed_when: false
